import { supabase } from "./supabaseClient";
import { fetchTopics, logSession } from "./learningHub";

export function manilaTodayISO() {
  return new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Manila" }).format(new Date());
}

/**
 * Today's module — generated by Claude on the first call of the day, then cached in Supabase.
 * force: generate a fresh one that replaces today's.
 */
export async function fetchTodayModule({ force = false } = {}) {
  const { data, error } = await supabase.functions.invoke("generate-learning-module", { body: force ? { force: true } : {} });
  if (error) {
    // FunctionsHttpError carries the function's JSON body on error.context.
    const detail = await error.context?.json?.().catch(() => null);
    throw new Error(detail?.error ?? error.message ?? "Couldn't load today's module.");
  }
  if (!data?.module) throw new Error(data?.error ?? "No module returned.");
  return data.module;
}

export async function fetchModuleHistory() {
  const { data, error } = await supabase
    .from("learning_hub_modules")
    .select("*")
    .order("generated_date", { ascending: false });
  if (error) throw error;
  return data ?? [];
}

export async function fetchActiveTopic() {
  const topics = await fetchTopics();
  return (
    topics
      .filter((t) => t.status === "active")
      .sort((a, b) => (b.updated_at ?? "").localeCompare(a.updated_at ?? ""))[0] ?? null
  );
}

// Consecutive days, ending today, with a logged module — used for the
// streak when there's no active learning topic to hold one.
function streakFromModules(modules) {
  const logged = new Set(modules.filter((m) => m.logged_today).map((m) => m.generated_date));
  let streak = 0;
  const day = new Date(`${manilaTodayISO()}T00:00:00Z`);
  while (logged.has(day.toISOString().slice(0, 10))) {
    streak++;
    day.setUTCDate(day.getUTCDate() - 1);
  }
  return streak;
}

/**
 * Marks today's module logged and advances the active topic's streak
 * (learning_topics.current_streak / last_session_date). Returns the new streak.
 */
export async function logModuleSession(module) {
  const { error } = await supabase.from("learning_hub_modules").update({ logged_today: true }).eq("id", module.id);
  if (error) throw error;
  const topic = await fetchActiveTopic();
  if (topic) {
    const updated = await logSession(topic.id, { progressPercent: topic.progress_percent });
    return updated.current_streak;
  }
  return streakFromModules(await fetchModuleHistory());
}

export async function currentStreak() {
  const topic = await fetchActiveTopic();
  if (topic) return topic.current_streak ?? 0;
  return streakFromModules(await fetchModuleHistory());
}

export async function saveTopicRequest(text) {
  const { data: auth } = await supabase.auth.getUser();
  const { error } = await supabase.from("learning_hub_requests").insert({
    user_id: auth.user?.id,
    request_text: text,
    requested_date: manilaTodayISO(),
  });
  if (error) throw error;
}
